### ISSUE TITLE
Name robot

### ISSUE THREAD

**Issue by rbonghi** [rbonghi/4UDE#1]
Help me to find a new name for this robot.
Write here your idea! :+1:

**Comment by rbonghi** [comment]
D-Robot @Myzhar

**Comment by Myzhar** [comment]
Anche D-Bot ;)

**Comment by gbr1** [comment]
prova a fare un acronimo ;)

**Comment by gbr1** [comment]
Xrobot a quanto pare è un'aspirapolvere russa...https://www.youtube.com/watch?v=3hr_c7H4qTs

**Comment by rbonghi** [comment]
The name is: **4UDE**

acronym for For Unmanned Discovering of Enviroments (special thx for @gbr1 :smile: )
Now I'll change name a this repo.
